---
version: "2.0"
services:
  minimal:
    image: ghcr.io/akash-network/ubuntu-2404-ssh:1
    expose:
      - port: 22
        as: 22
        to:
          - global: true
    env:
      - >-
        SSH_PUBKEY=$(ID_RSA_PUB)
profiles:
  compute:
    minimal:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        minimal:
          denom: uakt
          amount: 10000
deployment:
  minimal:
    dcloud:
      profile: minimal
      count: 1