---
version: "2.0"
services:
  nginx-ssl:
    image: nginx:1.27
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: myendpointa
      - port: 443
        as: 443
        to:
          - global: true
            ip: myendpointa
    command:
      - bash
      - "-c"
    args:
      - >-
        if [ -f /etc/nginx-persistent/nginx.conf ]; then
            echo "nginx.conf already exists";
        else
            echo "Get NGINX config from $NGINX_CONF_URL";
            wget $NGINX_CONF_URL -O /etc/nginx-persistent/nginx.conf;
        fi

        while [ "$FIRST_START" = true ]; do
            echo "Please set the A Record in your DNS to your leased IP and update the SDL with FIRST_START=false";
            sleep 20;
        done

        cp /etc/nginx-persistent/nginx.conf /etc/nginx/nginx.conf;

        apt-get update; apt-get upgrade -y; apt install -y certbot
        python3-certbot-nginx wget;

        certbot --nginx -d $DOMAIN --non-interactive --agree-tos
        --register-unsafely-without-email;

        service nginx stop; nginx -g "daemon off;"
    env:
      - DOMAIN=YOURDOMAIN.COM
      - NGINX_CONF_URL=
      - FIRST_START=true
    params:
      storage:
        data:
          mount: /etc/nginx-persistent
          readOnly: false
profiles:
  compute:
    nginx-ssl:
      resources:
        cpu:
          units: 1
        memory:
          size: 4Gi
        storage:
          - size: 5Gi
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        nginx-ssl:
          denom: uakt
          amount: 1000
deployment:
  nginx-ssl:
    dcloud:
      profile: nginx-ssl
      count: 1
endpoints:
  myendpointa:
    kind: ip
